export default {
  search_products: 'Search Products...',
  number_of_records_per_page: '# of records per page',
  change_language: 'Change Language',
  category: {
    toolbox: 'Toolbox',
    beverages: 'Beverages',
    accessories: 'Accessories',
    electronics: 'Electronics',
    clothes: 'Clothes',
    home_and_furniture: 'Home and Furniture',
    beauty_and_personal_care: 'Beauty and Personal Care',
    books_and_literature: 'Books and Literature',
    sports_and_outdoors: 'Sports and Outdoors',
    toys_and_games: 'Toys and Games',
    automotive: 'Automotive',
    health_and_wellness: 'Health and Wellness'
  },
  products: {
    toolbox: 'Toolbox',
    beverages: 'Beverages',
    accessories: 'Accessories',
    garden_tools: 'Garden Tools',
    home_decor: 'Home Decor',
    electronics: 'Electronics',
    kitchen_appliances: 'Kitchen Appliances',
    outdoor_furniture: 'Outdoor Furniture',
    clothing: 'Clothing',
    toys: 'Toys',
    power_tools: 'Power Tools',
    fitness_equipment: 'Fitness Equipment',
    smart_home_devices: 'Smart Home Devices',
    pet_supplies: 'Pet Supplies',
    art_and_craft_supplies: 'Art and Craft Supplies',
    home_security_systems: 'Home Security Systems',
    books: 'Books',
    car_accessories: 'Car Accessories',
    office_supplies: 'Office Supplies',
    musical_instrument: 'Musical Instrument'
  }
};